<a href="https://colab.research.google.com/github/alxmart/Scalars-Vectors-Matrices-Tensors/blob/master/Scalars_Vectors_Matrices_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy

# Scalar code example
x = 5

# Vector code example
v = numpy.array([1, 2, 3, 4])

# Matrix code example
m = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [50]:
x

5

In [51]:
v

array([1, 2, 3, 4])

In [52]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
import numpy as np

# A 0-D tensor would be a scalar
x0d_tensor_scalar = 5

# A 1-D tensor would be a vector
x1d_tensor_vector = numpy.array([1, 2, 3])

#A 2-D tensor would be a matrix
x2d_tensor_matrix = numpy.array([[1, 2], [3, 4], [5, 6]])

# A 3-D tensor would be a "cube" or a "stack" of matrices
x3d_tensor_cube = numpy.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"x0d / Tensor_Scalar:\n {x0d_tensor_scalar}\n===============\n")

print(f"x1d / Tensor_Vector:\n {x1d_tensor_vector}\n===============\n")

print(f"x2d: / Tensor_Matrix\n {x2d_tensor_matrix}\n===============\n")

print(f"x3d: / Tensor_Cube\n  {x3d_tensor_cube}\n===============\n")



x0d / Tensor_Scalar:
 5

x1d / Tensor_Vector:
 [1 2 3]

x2d: / Tensor_Matrix
 [[1 2]
 [3 4]
 [5 6]]

x3d: / Tensor_Cube
  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

